# Generated by Django 4.2 on 2024-08-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_payment_link_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Оплата наличными"), ("transfer", "Перевод на счет")],
                max_length=50,
                null=True,
                verbose_name="тип оплаты",
            ),
        ),
    ]
